version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to amazon ECR...
      - $(aws ecr get-login --no-include-email --region=$AWS_DEFAULT_REGION)
  build:
    commands:
      - echo Build Started on `date`
      - echo Building the docker image...
      - docker build -t cms-products-microservice .
      - docker tag cms-products-microservice:latest 288519183534.dkr.ecr.ap-south-1.amazonaws.com/cms-products-microservice:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 288519183534.dkr.ecr.ap-south-1.amazonaws.com/cms-products-microservice:latest
